### PR TITLE
Initial scratch bugfix

### LINKED ISSUE #135: Removing and then restoring source code fails to restore the diff result
https://decomp.me/scratch/UpZ6Q

Remove the first function here and notice the diff change. Then try to add it back and the diff does not update.

### PR DESCRIPTION
**Pull request by ethteck**
Fixes #135 

also makes it a lot less annoying to do local development, changing cookie settings in debug mode

### CODE REVIEW

File: frontend/src/api.ts [hunk 1]
```diff
@@ -259,7 +259,9 @@ export function useScratch(slugOrUrl: string): {
     const setScratch = useCallback((partial: Partial<Scratch>) => {
         const scratch = Object.assign({}, localScratch, partial)
 
-        if (!dequal(scratch, savedScratch)) {
+        if (dequal(scratch, savedScratch)) {
```
Comment (nanaian) [inline frontend/src/api.ts:262]: The reason for this was to not force a rerender if the saved scratch and the serverside scratch are already equal. It's weird to me that this would be the cause of a bug, and this "fix" certainly seems logically wrong.

Comment (nanaian) [reply frontend/src/api.ts:262]: Try testing the live viewing of someone else editing a scratch, this change probably breaks it
